Гельбарт Лев НММбд-01-22

Задание 2

Сначала пользователь с клавиатуры вводит значения ширины и высоты двойного массива, затем с клавиатуры побуквенно заполняет массив "словаря" и массив искомого слова.

In [41]:
m=int(input("Введите количество букв в словах: "))
n=int(input("Введите количество слов: "))
a = []
for i in range(n):
    a.append([0] * m)
    
for i in range(n):
    for j in range(m):
        a[i][j]=input("Введите букву слова для словаря: ")
print(a)        

b = []
for i in range(m):
    element = input("Введите букву слова для поиска: ")
    b.append(element)
print(b)

Введите количество букв в словах: 3
Введите каоличество слов: 2
Введите букву слова для словаря: м
Введите букву слова для словаря: а
Введите букву слова для словаря: г
Введите букву слова для словаря: г
Введите букву слова для словаря: а
Введите букву слова для словаря: д
[['м', 'а', 'г'], ['г', 'а', 'д']]
Введите букву слова для поиска: т
Введите букву слова для поиска: о
Введите букву слова для поиска: к
['т', 'о', 'к']


Функция посимвольно сверяет элементы "словаря" и искомого слова.

In [42]:
def search(a, b):
    k=0
    for i in range (n):
        for j in range (m): 
            if a[i][j]==b[j]:
                k+=1
            if k==m:
                return(True)
                break
    if k != m:
        return(False)

In [43]:
if search(a,b):
    print('Слово есть')
else:
    print('Слова нет')

Слова нет


Задание 3

Сначала создаем список 20 случайных чисел от 1 до 10.

In [96]:
from random import randint

c=[]
for i in range(20):
    c.append(randint(1, 10))
print(c)

[1, 4, 3, 7, 3, 7, 5, 9, 6, 6, 2, 2, 10, 7, 8, 8, 6, 4, 2, 10]


In [ ]:
Функция создает пустой список, он будет постепенно пополняться. Если числа нет в этом новом списке, оно туда добавится.

In [97]:
def RemoveDouble(c):
    d = []
    for i in c:
        if i not in d:
            d.append(i)
    return(d)

In [98]:
print(RemoveDouble(c))

[1, 4, 3, 7, 5, 9, 6, 2, 10, 8]


Задание 1

Создаем массив 4х4, функцию основываем на сортировке пузырьком, но делаем ее только по одному заранее выбранному столбцу.
Реверсом определяем направление течения пузырька

In [116]:
import numpy as np

e=np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])

def sort(e, f, reverse):
    m = e.shape[0]
    n = e.shape[1]
    r = []
    for i in range (m):
        r.append(e[i, f])
    swap = True
    while swap:
        swap = False
        for i in range(len(r)-1):
            if reverse == 0:
                if r[i] > r[i+1]:
                    r[i], r[i+1] = r[i+1], r[i]
            if reverse == 1:
                if r[i] < r[i+1]:
                    r[i], r[i+1] = r[i+1], r[i]
    g=[]
    for i in range(m):
        for j in range(m):
            if r[i]==e[j][f]:
                print(e[j])
                g.append(e[j])
    return(g)

In [117]:
print(sort(e, 1, 0))

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15])]


Задание 5

Здесь мы будем применять метод быстрой сортировки, так как в пункте 5 основного задания он показал себя самым эффективным
при сортировке списков, в которых маленькие значения находятся в конце.

In [ ]:
from random import randint
from time import sleep

 
def partition(nums, low, high):
    # Выбираем средний элемент в качестве опорного
    # Также возможен выбор первого, последнего
    # или произвольного элементов в качестве опорного
    pivot = nums[(low + high) // 2]
    i = low - 1
    j = high + 1
    while True:
        i += 1
        while nums[i] < pivot:
            i += 1

        j -= 1
        while nums[j] > pivot:
            j -= 1

        if i >= j:
            return j

        # Если элемент с индексом i (слева от опорного) больше, чем
        # элемент с индексом j (справа от опорного), меняем их местами
        nums[i], nums[j] = nums[j], nums[i]

def quick_sort(nums):
    # Создадим вспомогательную функцию, которая вызывается рекурсивно
    def _quick_sort(items, low, high):
        if low < high:
            # This is the index after the pivot, where our lists are split
            split_index = partition(items, low, high)
            _quick_sort(items, low, split_index)
            _quick_sort(items, split_index + 1, high)

    _quick_sort(nums, 0, len(nums) - 1)

5 раз наш код будет с перерывом в 1 секунду добавлять случайный элемент в массив, и тут же он будет сортироваться.

In [132]:
num =[]
for i in range(100):
    num.append(i+1)
seconds_left = 5
while seconds_left > 0:
        num.append(randint(1, 100))
        print('Raw ', num)
        quick_sort(num)
        print('Sorted', num)
        seconds_left -= 1
        sleep(1)

Raw  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 68]
Sorted [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
Raw  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 5